### ISSUE TITLE
Charsets, languages, MIME types stats broken

### ISSUE THREAD

**Issue by tfmorris** [commoncrawl/cc-crawl-statistics#1]
These pages have vestigial tables which look like they're meant to be includes of the related HTML files in the same directory, but they don't render properly, rendering instead as:

layout | table_include | table_sortlist
-- | -- | --
table | languages-top-200.html | {sortList: [[1,1]]}

**Comment by tfmorris** [comment]
Actually, they look fine on the web site, so I guess they're just not intended for viewing here in the repo.

**Comment by sebastian-nagel** [comment]
That's kind of an `#include` for the Jekyll / github-pages site generator, the templates are found in [_layouts](/commoncrawl/cc-crawl-statistics/tree/master/_layouts). The aim is to have sortable tables - I didn't find a way to do this with plain mark-down.
