### ISSUE TITLE
How does Common Crawl curate the list of domains for crawling?

### ISSUE THREAD

**Issue by phongiswindy** [commoncrawl/cc-crawl-statistics#2]
Sorry if I might have missed it, but could someone please point me to where I could find a post/Q&A which explains how Common Crawl curated all of the domains crawled every month?
Are these domains from zonefiles provided by several sources (e.g., ICANN)? Or Are they extracted from previously crawled data, and if so how was the very first list of domains curated?
Thank you!

**Comment by sebastian-nagel** [comment]
Hi @phongiswindy, could you post this question on the Common Crawl user group at
     https://groups.google.com/forum/#!forum/common-crawl ? Thanks!
There are already a few posts which answer your question partially: please start with [this one](https://groups.google.com/d/topic/common-crawl/OJW0g2PBVeM/discussion) others are linked from there. Thanks!
