### ISSUE TITLE
Hostname counts

### ISSUE THREAD

**Issue by edsu** [commoncrawl/cc-crawl-statistics#6]
Maybe I'm just missing it (very likely), but it doesn't look like the [current site](https://commoncrawl.github.io/cc-crawl-statistics/) provides visibility into the top hostnames? But the README.md here seems to indicate hostnames are among the things that are counted? I was going to run some Athena queries to get them and try to get a view into them but was wondering if it might make sense to try to add a view like that here. I understand that there are LOTS of them and perhaps that is why they are missing...

**Comment by sebastian-nagel** [comment]
Thanks. Definitely not a bad idea...

> hostnames are among the things that are counted

Yes. Counts for all host names are included in the output of step 1 (also on S3, eg. s3://commoncrawl/crawl-analysis/CC-MAIN-2021-10/count/part-00000.bz2 .. part-00009.bz2, 10 files in total). The top 500 are even included in the output of step 2. Wouldn't be a problem to add the counts of the latest crawl to the statistics site. But I'd rather take the top domain names:
```
  9672247    9635861   377522  blogspot.com
  7482999    7467689      638  wikipedia.org
  6850618    6812981   360226  wordpress.com
  5062770    5005722    21377  livejournal.com
  2969481    2962785    44339  fc2.com
  2245946    2236262    12506  free.fr
  2241479    2230149      432  europa.eu
  1954628    1948812      386  yahoo.com
  1421179    1320291    16702  pixnet.net
  1246722    1218748      204  google.com
```
Columns are: successful page captures, unique URLs, unique host names. The counts of registered domains are more meaningful and robust compared to counts per host name.

> I understand that there are LOTS of them

Indeed, there are too many unique host or domain names to show them all on a static HTML page (more than 50 million resp. 30 million every month),

But I'll add a list of top domains together with the updates for the April crawl. Will also put a note to
[README#step-3-plot-the-data](/commoncrawl/cc-crawl-statistics#step-3-plot-the-data) how to get the full list.

> run some Athena queries

Nice. For the long term the goal is to replace the MapReduce jobs by a series of Athena/Presto SQL queries. It'll be easier to maintain, more transparent, reproducible and extensible. See also our sample list of [queries](//github.com/commoncrawl/cc-index-table#query-the-table-in-amazon-athena) or [Jupyter notebooks](//github.com/commoncrawl/cc-notebooks).

**Comment by edsu** [comment]
That would be great if you could add some instructions on how to get the host and/or domain statistics that are already available. I took a look at one of the host stats files s3://commoncrawl/crawl-analysis/CC-MAIN-2021-10/count/part-00000.bz2 and was a bit confused about the format of those files:

```
[13,"sag",66]   525
[13,"smo",66]   [8840,8826]
[13,"srp",66]   [5611237,5579075]
[13,"ssw",66]   [983,976]
[13,"tat",66]   [230614,230248]
[13,"tel",66]   [453066,451918]
[13,"ton",66]   [1780,1777]
[2,"%d0%bc%d0%b8%d0%bb%d0%b0%d0%bd%d0%be63.%d1%80%d1%84",66]    1
[2,"%d1%81%d0%b5%d1%82%d1%8c%d0%ba%d0%be%d0%bc.%d1%80%d1%84",66]        1
[2,"0-0-0.com",66]      5
[2,"0-0.nl",66] 1
[2,"0-01.ru",66]        1
[2,"0-1.a100.nthosting.ru",66]  27
[2,"0-100.net",66]      1
[2,"0-12linemen.blogspot.com",66]       1
[2,"0-16.xn--p1ai",66]  16
[2,"0-21.ir",66]        1
```

Similarly the files that get_stats.sh fetches:

```
["surt_domain","au,com,tripadvisor","CC-MAIN-2018-34"]  [246991,243129,1]
["surt_domain","com,tvguide","CC-MAIN-2018-34"] [187298,182054,1]
["surt_domain","com,bhphotovideo","CC-MAIN-2018-34"]    [254789,253421,1]
["surt_domain","com,fiverr,block","CC-MAIN-2018-34"]    [255368,255368,1]
["surt_domain","fm,last","CC-MAIN-2018-34"]     [245870,245574,1]
["surt_domain","com,hubpages","CC-MAIN-2018-34"]        [255798,252106,1]
["surt_domain","com,lyricsmode","CC-MAIN-2018-34"]      [210810,196540,1]
["surt_domain","com,duolingo,forum","CC-MAIN-2018-34"]  [423018,330950,1]
["surt_domain","com,iheart","CC-MAIN-2018-34"]  [200382,200065,1]
["surt_domain","com,yellowpages","CC-MAIN-2018-34"]     [471790,467543,2]
```

I was mostly confused by the numbers in the second [...] on each line?

**Comment by sebastian-nagel** [comment]
Yes, I'll add a short description.

The numbers in the second row (the value row) are: [number of page captures, unique URLs, unique host names]. If a trailing number is equal to the number in front it is left away: `1` means: one page capture of one URL from one host, see [MultiCount](/commoncrawl/cc-crawl-statistics/blob/9c6921d76fc1e4c4c0438c478835488752b70d79/crawlstats.py#L325). Frankly, I consider this compression (and also that the enum int value is used in the keys of the count output) as an over-optimization - too complex although it saves some space, esp. in the intermediate map output which isn't compressed at all or using a fast but less space-reducing codec (usually snappy). But as said, the plan is to replace the MapReduce jobs.

**Comment by sebastian-nagel** [comment]
Done, see [top-500 domains page](https://commoncrawl.github.io/cc-crawl-statistics/plots/domains.html).
