### ISSUE TITLE
The indices for the monthly crawl enumeration will soon overflow

### ISSUE THREAD

**Issue by pjox** [commoncrawl/cc-crawl-statistics#7]
https://github.com/commoncrawl/cc-crawl-statistics/blob/85d3ec20bf94a8a3198ae27d4f6d4b70f6fd27e1/crawlstats.py#L38C1-L51C37

Indices 88 to 99 in `class MonthlyCrawl` are allocated to the oldest crawls, as the latest crawl (`CC-MAIN-2023-50`) is already number `84`, we are quickly running out of indices.

**Comment by thunderpoot** [comment]
From @sebastian-nagel
> Just continue with 100. I've never thought that the cc-crawl-statistics will cover 100 or more crawls.
